In [3]:
import pandas as pd
df = pd.read_csv(r'D:\MLOPSS\Project 1\ev_battery_synth.csv')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   battery_id                 15000 non-null  object
 1   manufacturer               14315 non-null  object
 2   chemistry                  14256 non-null  object
 3   capacity_kWh               14268 non-null  float64
 4   charge_cycles              14311 non-null  float64
 5   avg_temp_celsius           14282 non-null  float64
 6   discharge_rate_c           14280 non-null  float64
 7   charge_rate_c              14289 non-null  float64
 8   avg_soc_percent            14241 non-null  float64
 9   storage_time_months        14259 non-null  float64
 10  fast_charge_ratio          14254 non-null  float64
 11  calendar_age_years         14203 non-null  float64
 12  capacity_retained_percent  14249 non-null  float64
dtypes: float64(10), object(3)
memory usage: 1.5+ MB

In [5]:
df.describe()

,capacity_kWh,charge_cycles,avg_temp_celsius,discharge_rate_c,charge_rate_c,avg_soc_percent,storage_time_months,fast_charge_ratio,calendar_age_years,capacity_retained_percent
count,14268.000000,14311.000000,14282.000000,14280.000000,14289.000000,14241.000000,14259.000000,14254.000000,14203.000000,14249.000000
mean,74.831688,724.540354,24.836594,1.060485,1.017919,55.178979,3.962192,0.273791,1.997541,87.059668
std,14.809087,398.426835,8.644186,0.498338,0.360305,14.923134,3.957581,0.175465,1.977227,6.587419
min,40.000000,50.000000,-9.940000,0.500000,0.500000,10.000000,0.000000,0.000000,0.100000,25.010000
25%,64.507500,467.500000,19.940000,0.584000,0.731000,45.040000,1.100000,0.132000,0.570000,84.000000
50%,74.900000,655.000000,25.030000,0.989000,0.997000,55.410000,2.700000,0.245000,1.380000,87.840000
75%,85.030000,880.000000,30.070000,1.393000,1.267000,65.430000,5.500000,0.390000,2.770000,91.050000
max,120.000000,2898.000000,50.000000,3.303000,2.534000,90.000000,24.000000,0.938000,12.000000,124.990000

In [6]:
df.isnull().sum()

battery_id                     0
manufacturer                 685
chemistry                    744
capacity_kWh                 732
charge_cycles                689
avg_temp_celsius             718
discharge_rate_c             720
charge_rate_c                711
avg_soc_percent              759
storage_time_months          741
fast_charge_ratio            746
calendar_age_years           797
capacity_retained_percent    751
dtype: int64

In [7]:
#Dropped Battery_ID column 
df=df.drop('battery_id', axis=1)

In [8]:
df.head()

,manufacturer,chemistry,capacity_kWh,charge_cycles,avg_temp_celsius,discharge_rate_c,charge_rate_c,avg_soc_percent,storage_time_months,fast_charge_ratio,calendar_age_years,capacity_retained_percent
0,Panasonic,NMC,65.54,1524.0,26.61,1.507,0.500,51.96,0.1,0.155,1.58,81.75
1,Samsung SDI,LFP,NaN,1072.0,16.82,0.850,0.927,80.76,11.0,0.466,3.44,81.93
2,BYD,LFP,99.99,807.0,6.27,0.751,1.232,74.73,3.5,0.058,0.23,89.75
3,CATL,NMC,85.96,681.0,28.65,0.788,1.070,30.95,0.2,0.332,3.43,84.41
4,Tesla,NMC,69.85,476.0,41.57,0.683,0.607,59.67,3.6,0.307,0.34,87.04

In [9]:
# df_clean = df.dropna(subset=['manufacturer','chemistry'])
# df_clean.isnull().sum()
df['manufacturer'] = df['manufacturer'].fillna('Unknown')
df['chemistry'] = df['chemistry'].fillna('Unknown')
df_clean= df
df_clean.isnull().sum()

manufacturer                   0
chemistry                      0
capacity_kWh                 732
charge_cycles                689
avg_temp_celsius             718
discharge_rate_c             720
charge_rate_c                711
avg_soc_percent              759
storage_time_months          741
fast_charge_ratio            746
calendar_age_years           797
capacity_retained_percent    751
dtype: int64

In [10]:
len(df_clean)

15000

In [11]:
## Using lambda function and groupby to fill up the null values by grouping manufacturer and chemistry 
#transform iterates through each
numeric_cols = df_clean.select_dtypes(include=['number']).columns 
print(numeric_cols)

df_clean[numeric_cols] = df_clean.groupby(['manufacturer','chemistry'])[numeric_cols].transform(lambda x:x.fillna(x.median()))

Index(['capacity_kWh', 'charge_cycles', 'avg_temp_celsius', 'discharge_rate_c',
       'charge_rate_c', 'avg_soc_percent', 'storage_time_months',
       'fast_charge_ratio', 'calendar_age_years', 'capacity_retained_percent'],
      dtype='object')

In [12]:
df_clean.isnull().sum()

manufacturer                 0
chemistry                    0
capacity_kWh                 0
charge_cycles                0
avg_temp_celsius             0
discharge_rate_c             0
charge_rate_c                0
avg_soc_percent              0
storage_time_months          0
fast_charge_ratio            0
calendar_age_years           0
capacity_retained_percent    0
dtype: int64

In [13]:
df_clean = df.dropna()

In [14]:
len(df_clean)

15000

In [15]:
df_clean['manufacturer'].unique()
df = df_clean

In [16]:
#Now Encoding the categorical data 
from sklearn.preprocessing import LabelEncoder

from sklearn.preprocessing import LabelEncoder 

label_encoders = {}
categorical_cols = ['manufacturer','chemistry']

for col in categorical_cols:
    le = LabelEncoder()
    df[col+'_encoded'] = le.fit_transform(df[col])
    label_encoders[col] = le

df= df.drop(categorical_cols,axis=1)

In [17]:
df.head()

,capacity_kWh,charge_cycles,avg_temp_celsius,discharge_rate_c,charge_rate_c,avg_soc_percent,storage_time_months,fast_charge_ratio,calendar_age_years,capacity_retained_percent,manufacturer_encoded,chemistry_encoded
0,65.540,1524.0,26.61,1.507,0.500,51.96,0.1,0.155,1.58,81.75,3,2
1,75.235,1072.0,16.82,0.850,0.927,80.76,11.0,0.466,3.44,81.93,4,0
2,99.990,807.0,6.27,0.751,1.232,74.73,3.5,0.058,0.23,89.75,0,0
3,85.960,681.0,28.65,0.788,1.070,30.95,0.2,0.332,3.43,84.41,1,2
4,69.850,476.0,41.57,0.683,0.607,59.67,3.6,0.307,0.34,87.04,5,2

In [18]:
#Encoding Completed

In [19]:
# Outlier removal using Isolation Forest
from sklearn.ensemble import IsolationForest
import pandas as pd

print("="*60)
print("OUTLIER REMOVAL USING ISOLATION FOREST")
print("="*60)

# Step 1: Select numeric columns
numeric_cols = df.select_dtypes(include=['number']).columns
df_numeric = df[numeric_cols]

print(f"\nOriginal Dataset: {len(df)} rows")
print(f"Numeric columns used: {len(numeric_cols)}")

# Step 2: Check for nulls
if df_numeric.isnull().any().any():
    print("\n⚠ Warning: Nulls detected in numeric columns!")
    print(df_numeric.isnull().sum()[df_numeric.isnull().sum() > 0])
    print("Filling nulls with median before outlier detection...")
    df_numeric = df_numeric.fillna(df_numeric.median())

# Step 3: Initialize Isolation Forest
iso_forest = IsolationForest(
    contamination=0.05,      # 5% expected outliers
    random_state=42,
    n_estimators=120
)

# Step 4: Fit and predict
print("\nDetecting outliers...")
outlier_labels = iso_forest.fit_predict(df_numeric)

# Step 5: Filter out outliers
df_clean = df[outlier_labels == 1].copy()  # ← IMPORTANT: .copy()

# Step 6: Results
outliers_removed = len(df) - len(df_clean)
print(f"\n{'='*60}")
print("RESULTS:")
print(f"{'='*60}")
print(f"Outliers detected: {outliers_removed} ({outliers_removed/len(df)*100:.2f}%)")
print(f"Clean dataset: {len(df_clean)} rows ({len(df_clean)/len(df)*100:.2f}%)")

# Step 7: CRITICAL - Update df to use cleaned version
df = df_clean.copy()  # ← THIS IS THE FIX!

print(f"\n✓ Outliers removed. Working with {len(df)} rows now.")
print("="*60)

============================================================
OUTLIER REMOVAL USING ISOLATION FOREST
============================================================

Original Dataset: 15000 rows
Numeric columns used: 12

Detecting outliers...

============================================================
RESULTS:
============================================================
Outliers detected: 750 (5.00%)
Clean dataset: 14250 rows (95.00%)

✓ Outliers removed. Working with 14250 rows now.
============================================================

In [20]:
#outlier removal is done... calculated expectation value = 3000 removed 2250
df = df_clean

In [21]:
df.columns

Index(['capacity_kWh', 'charge_cycles', 'avg_temp_celsius', 'discharge_rate_c',
       'charge_rate_c', 'avg_soc_percent', 'storage_time_months',
       'fast_charge_ratio', 'calendar_age_years', 'capacity_retained_percent',
       'manufacturer_encoded', 'chemistry_encoded'],
      dtype='object')

In [22]:
from sklearn.preprocessing import PowerTransformer
import pandas as pd

print("="*60)
print("NORMALIZATION PIPELINE")
print("="*60)

# Step 1: Correctly separate target and encoded features
TARGET_COLUMN = 'capacity_retained_percent'
ENCODED_COLUMNS = ['manufacturer_encoded', 'chemistry_encoded']

# Extract target (y)
y = df[TARGET_COLUMN].copy()

# Extract features to normalize (exclude target and encoded)
columns_to_exclude = [TARGET_COLUMN] + ENCODED_COLUMNS
X = df.drop(columns_to_exclude, axis=1)

# Extract encoded features (to add back later)
X_encoded = df[ENCODED_COLUMNS].copy()

print(f"\n[1] Data Separation:")
print(f"    Features to normalize (X): {X.shape}")
print(f"    Encoded features: {X_encoded.shape}")
print(f"    Target (y): {y.shape}")

# Step 2: Select numeric columns
numeric_cols = X.select_dtypes(include=['number']).columns
print(f"\n[2] Numeric columns to normalize: {list(numeric_cols)}")

# Step 3: Check skewness before
print("\n[3] Skewness BEFORE normalization:")
print(X[numeric_cols].skew().sort_values(ascending=False))

# Step 4: Apply Yeo-Johnson transformation
print("\n[4] Applying Yeo-Johnson transformation...")
transformer = PowerTransformer(method='yeo-johnson', standardize=True)
X_normalized = transformer.fit_transform(X[numeric_cols])

# Step 5: Convert back to DataFrame
X_normalized_df = pd.DataFrame(
    X_normalized,
    columns=numeric_cols,
    index=X.index
)

# Step 6: Add back encoded columns (NOT target!)
X_final = pd.concat([X_normalized_df, X_encoded], axis=1)

# Step 7: Check skewness after
print("\n[5] Skewness AFTER normalization:")
print(X_final[numeric_cols].skew().sort_values(ascending=False))

# Step 8: Verify shapes
print("\n" + "="*60)
print("NORMALIZATION COMPLETE!")
print("="*60)
print(f"X_final (features only): {X_final.shape}")
print(f"y (target only): {y.shape}")
print(f"Shapes match: {X_final.shape[0] == y.shape[0]} ✓")

print(f"\nColumns in X_final:")
print(list(X_final.columns))
print(f"\nTarget variable name: {TARGET_COLUMN}")

============================================================
NORMALIZATION PIPELINE
============================================================

[1] Data Separation:
    Features to normalize (X): (14250, 9)
    Encoded features: (14250, 2)
    Target (y): (14250,)

[2] Numeric columns to normalize: ['capacity_kWh', 'charge_cycles', 'avg_temp_celsius', 'discharge_rate_c', 'charge_rate_c', 'avg_soc_percent', 'storage_time_months', 'fast_charge_ratio', 'calendar_age_years']

[3] Skewness BEFORE normalization:
storage_time_months    1.803248
calendar_age_years     1.785389
charge_cycles          1.222931
discharge_rate_c       0.752425
fast_charge_ratio      0.685847
charge_rate_c          0.390792
capacity_kWh           0.049198
avg_soc_percent       -0.091096
avg_temp_celsius      -0.341629
dtype: float64

[4] Applying Yeo-Johnson transformation...

[5] Skewness AFTER normalization:
avg_temp_celsius       0.103114
charge_cycles          0.076155
discharge_rate_c       0.064915
calendar_age_years     0.058124
fast_charge_ratio      0.048724
storage_time_months    0.015516
charge_rate_c          0.004419
capacity_kWh          -0.006321
avg_soc_percent       -0.008706
dtype: float64

============================================================
NORMALIZATION COMPLETE!
============================================================
X_final (features only): (14250, 11)
y (target only): (14250,)
Shapes match: True ✓

Columns in X_final:
['capacity_kWh', 'charge_cycles', 'avg_temp_celsius', 'discharge_rate_c', 'charge_rate_c', 'avg_soc_percent', 'storage_time_months', 'fast_charge_ratio', 'calendar_age_years', 'manufacturer_encoded', 'chemistry_encoded']

Target variable name: capacity_retained_percent

In [23]:
X_final.head()

,capacity_kWh,charge_cycles,avg_temp_celsius,discharge_rate_c,charge_rate_c,avg_soc_percent,storage_time_months,fast_charge_ratio,calendar_age_years,manufacturer_encoded,chemistry_encoded
0,-0.649942,1.968450,0.171888,1.027273,-1.651346,-0.238796,-1.837525,-0.629588,0.190570,3,2
1,0.033215,1.058970,-1.044043,-0.268034,-0.157662,1.830189,1.641881,1.186859,1.104507,4,0
2,1.740659,0.425216,-2.202016,-0.538191,0.699908,1.389829,0.309935,-1.475699,-1.405324,0,0
3,0.778889,0.084127,0.437706,-0.434066,0.261831,-1.679217,-1.696272,0.532295,1.101089,1,2
4,-0.345086,-0.553518,2.200531,-0.740290,-1.236457,0.306013,0.341182,0.391600,-1.196894,5,2

In [24]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor
from catboost import CatBoostRegressor
import warnings
warnings.filterwarnings('ignore')

In [25]:
#splitting the data 
X_train, X_test, y_train, y_test = train_test_split(X_final, y, test_size=0.2, random_state=42)
print(f"\nTrain set: {X_train.shape}")
print(f"Test set: {X_test.shape}")

models = {
    'Linear Regression': {
        'model': LinearRegression(),
        'params': {
            'fit_intercept': [True, False]
        }
    },
    
    'Decision Tree': {
        'model': DecisionTreeRegressor(random_state=42),
        'params': {
            'max_depth': [5, 10, 15, 20, None],
            'min_samples_split': [2, 5, 10],
            'min_samples_leaf': [1, 2, 4]
        }
    },
    
    'Random Forest': {
        'model': RandomForestRegressor(random_state=42),
        'params': {
            'n_estimators': [50, 100, 200],
            'max_depth': [10, 20, 30, None],
            'min_samples_split': [2, 5],
            'min_samples_leaf': [1, 2]
        }
    },
    
    'KNeighbors': {
        'model': KNeighborsRegressor(),
        'params': {
            'n_neighbors': [3, 5, 7, 9, 11],
            'weights': ['uniform', 'distance'],
            'p': [1, 2]
        }
    },
    
    'XGBoost': {
        'model': XGBRegressor(random_state=42, verbosity=0),
        'params': {
            'n_estimators': [100, 200, 300],
            'max_depth': [3, 5, 7],
            'learning_rate': [0.01, 0.1, 0.3],
            'subsample': [0.8, 1.0]
        }
    },
    
    'CatBoost': {
        'model': CatBoostRegressor(random_state=42, verbose=0),
        'params': {
            'iterations': [100, 200, 300],
            'depth': [4, 6, 8],
            'learning_rate': [0.01, 0.1, 0.3]
        }
    },
    
    'AdaBoost': {
        'model': AdaBoostRegressor(random_state=42),
        'params': {
            'n_estimators': [50, 100, 200],
            'learning_rate': [0.01, 0.1, 1.0]
        }
    }
}

Train set: (11400, 11)
Test set: (2850, 11)

In [26]:
results = []

for model_name, model_info in models.items():
    print(f"\n[Training] {model_name}...")
    
    # GridSearchCV
    grid_search = GridSearchCV(
        estimator=model_info['model'],
        param_grid=model_info['params'],
        cv=5,
        scoring='r2',
        n_jobs=-1,
        verbose=0
    )
    
    # Fit
    grid_search.fit(X_train, y_train)
    
    # Best model
    best_model = grid_search.best_estimator_
    
    # Predictions
    y_train_pred = best_model.predict(X_train)
    y_test_pred = best_model.predict(X_test)
    
    # Metrics
    train_r2 = r2_score(y_train, y_train_pred)
    test_r2 = r2_score(y_test, y_test_pred)
    train_rmse = np.sqrt(mean_squared_error(y_train, y_train_pred))
    test_rmse = np.sqrt(mean_squared_error(y_test, y_test_pred))
    train_mae = mean_absolute_error(y_train, y_train_pred)
    test_mae = mean_absolute_error(y_test, y_test_pred)
    
    # Store results
    results.append({
        'Model': model_name,
        'Best_Params': grid_search.best_params_,
        'Train_R2': train_r2,
        'Test_R2': test_r2,
        'Train_RMSE': train_rmse,
        'Test_RMSE': test_rmse,
        'Train_MAE': train_mae,
        'Test_MAE': test_mae,
        'Best_Model': best_model
    })
    
    print(f"  ✓ Best R2 Score: {test_r2:.4f}")
    print(f"  ✓ Best Params: {grid_search.best_params_}")

[Training] Linear Regression...
  ✓ Best R2 Score: 0.5286
  ✓ Best Params: {'fit_intercept': True}

[Training] Decision Tree...
  ✓ Best R2 Score: 0.4722
  ✓ Best Params: {'max_depth': 5, 'min_samples_leaf': 4, 'min_samples_split': 2}

[Training] Random Forest...
  ✓ Best R2 Score: 0.5785
  ✓ Best Params: {'max_depth': 10, 'min_samples_leaf': 2, 'min_samples_split': 5, 'n_estimators': 200}

[Training] KNeighbors...
  ✓ Best R2 Score: 0.4709
  ✓ Best Params: {'n_neighbors': 11, 'p': 2, 'weights': 'distance'}

[Training] XGBoost...
  ✓ Best R2 Score: 0.5994
  ✓ Best Params: {'learning_rate': 0.1, 'max_depth': 3, 'n_estimators': 100, 'subsample': 1.0}

[Training] CatBoost...
  ✓ Best R2 Score: 0.6062
  ✓ Best Params: {'depth': 4, 'iterations': 100, 'learning_rate': 0.1}

[Training] AdaBoost...
  ✓ Best R2 Score: 0.4188
  ✓ Best Params: {'learning_rate': 0.01, 'n_estimators': 50}

In [27]:
results_df = pd.DataFrame([{k: v for k, v in r.items() if k != 'Best_Model'} 
                           for r in results])

# Sort by Test R2 Score (descending)
results_df = results_df.sort_values('Test_R2', ascending=False)

# Display results
print("\n" + results_df.to_string(index=False))

# ============================================================
# STEP 5: Best Model Summary
# ============================================================
print("\n" + "="*70)
print("BEST MODEL SUMMARY")
print("="*70)

best_result = results_df.iloc[0]
best_model_name = best_result['Model']
best_model_obj = [r['Best_Model'] for r in results if r['Model'] == best_model_name][0]

print(f"\n🏆 Best Model: {best_model_name}")
print(f"   Test R² Score: {best_result['Test_R2']:.4f}")
print(f"   Test RMSE: {best_result['Test_RMSE']:.4f}")
print(f"   Test MAE: {best_result['Test_MAE']:.4f}")
print(f"\n   Best Parameters:")
for param, value in eval(best_result['Best_Params']).items():
    print(f"   - {param}: {value}")

# ============================================================
# STEP 6: Detailed Metrics Table
# ============================================================
print("\n" + "="*70)
print("DETAILED METRICS COMPARISON")
print("="*70)

metrics_df = results_df[['Model', 'Train_R2', 'Test_R2', 'Test_RMSE', 'Test_MAE']].copy()
metrics_df['Overfit'] = metrics_df['Train_R2'] - metrics_df['Test_R2']

print("\n" + metrics_df.to_string(index=False))

# ============================================================
# STEP 7: Save Best Model
# ============================================================
import pickle

# Save best model
with open('best_model.pkl', 'wb') as f:
    pickle.dump(best_model_obj, f)

print("\n" + "="*70)
print(f"✓ Best model ({best_model_name}) saved as 'best_model.pkl'")
print("="*70)

            Model                                                                           Best_Params  Train_R2  Test_R2  Train_RMSE  Test_RMSE  Train_MAE  Test_MAE
         CatBoost                                 {'depth': 4, 'iterations': 100, 'learning_rate': 0.1}  0.536762 0.606248    3.992845   3.323385   2.102602  2.040397
          XGBoost         {'learning_rate': 0.1, 'max_depth': 3, 'n_estimators': 100, 'subsample': 1.0}  0.553830 0.599425    3.918598   3.352057   2.073237  2.077933
    Random Forest {'max_depth': 10, 'min_samples_leaf': 2, 'min_samples_split': 5, 'n_estimators': 200}  0.700895 0.578512    3.208428   3.438444   1.825607  2.155466
Linear Regression                                                               {'fit_intercept': True}  0.457329 0.528632    4.321643   3.636215   2.493214  2.371747
    Decision Tree                       {'max_depth': 5, 'min_samples_leaf': 4, 'min_samples_split': 2}  0.427785 0.472234    4.437723   3.847603   2.690460  2.606424
       KNeighbors                                    {'n_neighbors': 11, 'p': 2, 'weights': 'distance'}  1.000000 0.470874    0.000000   3.852556   0.000000  2.575302
         AdaBoost                                           {'learning_rate': 0.01, 'n_estimators': 50}  0.361028 0.418842    4.689446   4.037536   2.953882  2.813316

======================================================================
BEST MODEL SUMMARY
======================================================================

🏆 Best Model: CatBoost
   Test R² Score: 0.6062
   Test RMSE: 3.3234
   Test MAE: 2.0404

   Best Parameters:

TypeError: eval() arg 1 must be a string, bytes or code object